name: Publish NuGet Package

on:
  push:
    branches:
      - master
  release:
    types:
      - published

permissions:
  contents: read

jobs:
  publish:
    name: Build and Publish NuGet
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4

      - name: Restore dependencies
        run: dotnet restore

      - name: Get version from .csproj
        id: get_version
        run: echo "VERSION=$(xmllint --xpath "string(//Project/PropertyGroup/Version)" **/LanScan.csproj)" >> $GITHUB_ENV


      - name: Check if version already exists on NuGet
        id: check_nuget
        run: |
          RESPONSE=$(curl -sL "https://api.nuget.org/v3-flatcontainer/YOUR_PACKAGE_NAME/index.json" | grep -o "$VERSION" || true)
          if [ -n "$RESPONSE" ]; then
            echo "Version $VERSION already exists on NuGet. Skipping publish."
            exit 0
          fi

      - name: Build project
        run: dotnet build LanScan/LanScan.csproj --configuration Release --no-restore

      - name: Pack NuGet package
        run: dotnet pack LanScan/LanScan.csproj --configuration Release --no-build --output .

      - name: Publish to NuGet
        run: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
